[package]
name = "baidupan"
version = "0.1.0"
authors = ["PeterDing <dfhayst@gmail.com>"]

[dependencies]
reqwest = "0.8"
url = "1.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lazy_static = "0.2"

baidu-pan-api = { path = "baidu-pan-api" }
